# Generated by Django 3.0.8 on 2020-08-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finxiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demandadepecas',
            table=None,
        ),
    ]
