# Generated by Django 3.0.8 on 2020-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finxiapp', '0004_auto_20200805_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandadepecas',
            name='contato_email',
            field=models.CharField(max_length=200, verbose_name='Email de contato'),
        ),
        migrations.AlterField(
            model_name='demandadepecas',
            name='contato_telefone',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='demandadepecas',
            name='endereco_entrega',
            field=models.CharField(max_length=200, verbose_name='Endereço de entrega'),
        ),
    ]
